---
- name: Create Dynamic Inventory
  hosts: localhost
  tasks:
    - name: Gather Instance Facts
      ec2_instance_facts:
        region: "{{ region }}"
        filters:
          instance-state-name: running
          "tag:Name": "*{{ app_name }}*"
      register: ec2_instance_facts_results

    - name: Debug ec2_instance_facts_results
      debug:
        var: ec2_instance_facts_results
        verbosity: 2

    - name: Create Dynamic Inventory
      add_host:
        name: "{{ item.tags.Name }}"
        groups: "{{ item.tags.Role }}"
        ansible_ssh_host: "{{ item.public_ip_address }}"
      with_items:
        - "{{ ec2_instance_facts_results.instances }}"

- name: Configure Tomcat on Instances
  hosts: tomcat
  become: yes
  tasks:
    - name: Ensure Hosts Are Running
      become: no
      wait_for:
        port: 22
        host: "{{ (ansible_ssh_host | default(ansible_host)) | default(inventory_hostname) }}"
        search_regex: OpenSSH
      connection: local

    - name: Configure JWS Repos
      copy:
        src: files/jws.repo
        dest: /etc/yum.repos.d/jws.repo

    - name: Install Packages
      yum:
        name:
          - "java"
          - "@jws5"
        state: latest
        update_cache: yes

    - name: Start Tomcat
      service:
        name: jws5-tomcat
        state: started
