---
- name: Create Dynamic Inventory
  hosts: localhost
  tasks:
    - name: Create Dynamic Inventory
      add_host:
        name: "{{ item.name }}.{{ app_name }}.{{ dns_zone }}"
        groups: "{{ item.role }}"
      with_items:
        - "{{ instances }}"

- name: Configure Tomcat on Instances
  hosts: tomcat
  become: yes
  tasks:
    - name: Ensure Hosts Are Running
      become: no
      wait_for:
        port: 22
        host: "{{ (ansible_ssh_host | default(ansible_host)) | default(inventory_hostname) }}"
        search_regex: OpenSSH
      connection: local

    - name: Deploy Latest WAR Artifact
      maven_artifact:
        group_id: "{{ maven_group_id }}"
        artifact_id: "{{ maven_artifact_id }}"
        extension: "{{ maven_extension }}"
        version: latest
        repository_url: "http://{{ nexus_server }}:{{ nexus_port }}/repository/{{ maven_repository }}/"
        dest: "/tmp"
        keep_name: yes
        mode: 0644
        group: root
        owner: root
      register: maven_artifact_results

    - name: Move WAR to Tomcat Webapps Folder
      command: "mv {{ maven_artifact_results.dest }} {{ tomcat_webapps }}"
