---
- name: Test AWS Credentials
  hosts: localhost
  tasks:
    - name: Get Instance Facts
      ec2_instance_facts:
        filters:
          "tag:Name": "{{ instance_name_filter }}"
      register: ec2_instance_facts

    - name: Debug ec2_instance_facts
      debug:
        var: ec2_instance_facts
